# Generated by Django 4.0.3 on 2022-05-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_alter_deletedcontacts_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deletedcontacts',
            old_name='phone',
            new_name='phone1',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='phone',
            new_name='phone1',
        ),
        migrations.AddField(
            model_name='deletedcontacts',
            name='phone2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='deletedcontacts',
            name='phone3',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='phone2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='phone3',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
