# Generated by Django 4.0.3 on 2022-06-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone1',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
